name: CI on IOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Checkout the git Repo
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Execute Test
          run: npm install -g appium@next

        - name: Check Appium Version
          run: appium -v

        - name: Run Appium in the background
          run: appium &>/dev/null &
            
          #npx wdio wdio.ios-wdioApp.conf.js