name: CI on IOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Checkout the git Repo
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 18

        - name: Install Dependencies
          run: npm install

        - name: Install latest Appium version
          run: npm install -g appium@next

        - name: Check WDIO Version
          run: npx wdio --version

        - name: Run Appium in the background
          run: appium &>/dev/null &
            
        - name: Execute WDIO Tests
          run: npx wdio wdio.ios-wdioApp.conf.js