name: CI on IOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Checkout the git Repo
          uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Execute Test
          run: npm install -g appium@next|
          run: appium -v
          run: appium &>/dev/null &
          run: npx wdio wdio.ios-wdioApp.conf.js